## 配置当前的环境信息
spring:
  profiles:
    active: @profiles.active@


#置为true开启调试模式，不进行加密
encrypt.debug: false
#RSA加密公钥
spring.encrypt.publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCB0QMnEMYE+Cm2mOQaLOFa+Et9H8hEGnmyiZWVpD4/XZM12M63siilKKvLcLMkjcBZDR9dNiMyvZV7bmbaIE1VLjfKVib5WClv5ZLJoC5VzE+w3ox11rLQSDxU6A3bj76Ac2fzwwBTWdfx0MYMkxMXVbCVlccmUibloAnyFFHQyQIDAQAB
#RSA加密私钥
spring.encrypt.privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIHRAycQxgT4KbaY5Bos4Vr4S30fyEQaebKJlZWkPj9dkzXYzreyKKUoq8twsySNwFkNH102IzK9lXtuZtogTVUuN8pWJvlYKW/lksmgLlXMT7DejHXWstBIPFToDduPvoBzZ/PDAFNZ1/HQxgyTExdVsJWVxyZSJuWgCfIUUdDJAgMBAAECgYAYeRHSFIxwNWSPwuUFtj5JyxNYJFy50g/tQ5jKnCsMARUWiqf144VcFX3FnZp4Iq0HXLzz8pfSIgGDQn3rUzmgt2wcwNlgL0PX6FfAWHIRHsk3ax5b+C9YaiABcxF2vvjrV+/fAn5P5qLSLZRNX7868dVXzsGKziT2UimLViiRPQJBAMO+6H9Oge4z9HNbpSDZnjhmwtQu0uUzi65+wbD8naLbaXPxDPPHNhxUsbf2HJWqMMz3nWnN4HKGzsDrOT9UQwcCQQCpxsQwcA5OljTZGVpoXT3+Z9Eriy2SbPWgImi8oe+dNBmR+UEkharyp+NIOy/epfL3CCDtOakBl0C5Xsy6zUmvAkAh0QdlhvCXcE5Y54o9hJr673XVJkm04xTMjoVzyBCLpBAxwYEVVGMavd7+AvypNn+7yUNelfyijHuHhJudPzddAkEAlBNQug6B6/kGTvPV7oCkuWdDAH97V+LAuNJKF3wFyU7PnomPT5Nl7g6QJUe6EK8comjsjvtjdIe/Y+5TEfpK8QJAcA5vvWR6lAqEwvM19VaVXE8j46Wzml7GcSbvU34uCxXIx3n1J2rjvXJfr8wyhbqzd4FukHrmicZHmGDUUwXJZA==
