server:
  servlet:
    context-path: /
  port: 10002

# Mybatis-Plus Config
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.langsin.oa.dto
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      insert-strategy: not_empty
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.46.45.207:3306/langsin_oa?autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: anchor
    password: Cnnho2020_Anchor
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      #最小连接
      minimum-idle: 10
      #最大连接
      maximum-pool-size: 100
      #最大空闲时间
      idle-timeout: 60000
      #连接池名
      pool-name: DatebookHikariCP
      #最大生命周期
      max-lifetime: 900000
      #连接超时时间
      connection-timeout: 15000
      #心跳检测
      connection-test-query: SELECT 'x' FROM DUAL

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
#日志相关

  #ehcache
cache:
  ehcache:
    config: classpath:ehcache.xml

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /verify/*
  # 匹配链接
  urlPatterns: /permission/*,/role/*,/user/*


logging:
  file: /data/anchor-mgmt-sys/logs

filePath: /data/file/
fileUrl: /files/
fileMap: /files/**

imgPath: http://syzbmgmt.cnnho.com/api/files/